# 1.Array

In [2]:
import numpy as np
from StringIO import StringIO

In [2]:
#创建Array类型
np.array([2,3,4,5])#创建一般数组
np.zeros((2,3))#创建初始化的0值数组
np.arange(10)#按顺序从0-9
np.arange(2,10,dtype=np.float)#指定区间和类型
np.arange(2,3,0.1)#指定间隔和区间
np.linspace(1.,4.,6)#创建线性数组并指定数组的个数
np.indices((4,4))#返回两个类型的矩阵

array([[[0, 0, 0, 0],
        [1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3]],

       [[0, 1, 2, 3],
        [0, 1, 2, 3],
        [0, 1, 2, 3],
        [0, 1, 2, 3]]])

In [3]:
#从文本中载入数据
data = "1,2,3\n4,5,6"#读取csv文件，一般为None，默认TAB或空格
np.genfromtxt(StringIO(data),delimiter=",")
data = "  1  2  3\n  4  5 67\n89012 4"#分割按固定长度
np.genfromtxt(StringIO(data),delimiter=3)
data = "1, abc , 2\n 3, xxx, 4"#自动去掉空格，设定字符串类型
np.genfromtxt(StringIO(data), delimiter=",", dtype="|S5", autostrip=True)#去掉空格
np.genfromtxt(StringIO(data), comments="#", delimiter=",")#忽略注释内容
np.genfromtxt(StringIO(data),skip_header=3,skip_footer=5)#截取指定行之间的数据
np.genfromtxt(StringIO(data),usecols=(0,-1))#选取指定列
np.genfromtxt(StringIO(data),names="a,b,c",usecols=("a","c"))#指定名字，按名字选取指定列
#选择数据类型

StopIteration: 

In [4]:
#设置命名
data = StringIO("1 2 3\n 4 5 6")
np.genfromtxt(data,names="A,B,C")
#数据中设置命名
data = StringIO("So it goes\n#a b c\n1 2 3\n4 5 6")
np.genfromtxt(data,skip_header=1,names=True)#直接设置为True
#重新设置
data = StringIO("1 2 3\n4 5 6")
ndtype = [('a',int),('b',float),('c',int)]
names = ["A","B","C"]
np.genfromtxt(data,names=names,dtype=ndtype)
#如果没有设置命名空间，则默认为"f%i",也可以有一个命名，空缺的按规则补足

array([(1, 2.0, 3), (4, 5.0, 6)], 
      dtype=[('A', '<i8'), ('B', '<f8'), ('C', '<i8')])

In [6]:
#转换数据内容，可以设置转换函数
convertfunc = lambda x:float(x.strip("%"))/100.
data ="1,2.3%,45.\n6,78.9%,0"
names = ("i","p","n")
#可以使用name作为列，使用转换函数
np.genfromtxt(StringIO(data),delimiter=",",names=names,converters={1:convertfunc})
#将丢失的值转换为0或者其他
data = "N/A,2,3\n4, ,???"
kwargs = dict(delimiter=",",
             dtype = int,
             names="a,b,c",
             missing_values={0:"N/A",'b':" ",2:"???"},
             filling_values={0:0,'b':0,2:-999})
np.genfromtxt(StringIO(data),**kwargs)

array([(0, 2, 3), (4, 0, -999)], 
      dtype=[('a', '<i8'), ('b', '<i8'), ('c', '<i8')])

### 其他类型的读取文件的函数
ndfromtxt: 默认设置 usemask = False,生成一个标准的numpy.ndarray

mafromtxt: 默认设置 usemask = True,生成一个标准的MaskedArray

recfromtxt:默认设置 dtype = None, 生成一个numpy.recarray(usemask=False),或者MaskedArray(usemaske=True)

recfromcsv:默认设置 delimiter = "," 功能和recfromtxt类似。


# 2.索引（Indexing）

In [17]:
#一维素索引（Single element indexing），索引不算最后一个元素
x = np.arange(10)
x[2]#返回第3个元素
x[-1]#返回倒数第1个元素
x[2:5]#返回第3个到第4个元素
x[:-7]#返回第1个到倒数第8个元素
x[1:7:2]#返回第2个元素和第6个元素之间，步长为2的元素

#多维数组元素索引（Single element indexing）
x.shape =(2,5)#将1维数组转换成2维数组
x[1,3]#返回第2行第4列的元素
x[1,-1]#范围第2行倒数第一个元素
x[0]#多维数组，返回第0行数据
x[0][2]#返回第1行第2列元素
y[1:5:2,::3]#返回一个切片矩阵

#一维数组索引
x = np.arange(10,1,-1)
x[np.array([3,3,1,8])]#从x中选择指定的元素，可以重复选取，返回一个结果，数组类型为[]中创建的属猪类型。
x[np.array([1,1],[2,3])]#返回一个二维数组

#二维数组索引
y[np.array([0,2,4]), np.array([0,1,2])] #挑选[0,0],[2,1],[4,2]这三个元素形成一个数组
y[np.array([0,2,4]), 1] #返回第2列的，0，2，4这几个元素并形成一个数组
y[np.array([0,2,4])]#返回第0行，第2行，第4行的数组。

#布林和mask索引数组
b = y>20#设置一个条件
y[b]#按照条件返回一个数组

[10  9  8  7  6  5  4  3  2]


In [7]:
x = np.arange(5)
x[:,np.newaxis]+x[np.newaxis,:]#np.newaxis增加一个占位行

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7],
       [4, 5, 6, 7, 8]])

In [11]:
z = np.arange(81).reshape(3,3,3,3)
print z[1,...,2]

[[29 32 35]
 [38 41 44]
 [47 50 53]]


In [16]:
#定义索引的值,
x = np.arange(0,50,10)
x[np.array([1,1,3,1])]+=1#不会增加3次，只会三次调取原始的数组而不是新的数组。

array([ 0, 11, 20, 31, 40])

In [22]:
#处理数量不定的数组
indices = (0,1,1,2)
z[indices]

14

In [24]:
#操作
a = np.array([1.0,2.0,3.0])
b = np.array([2.0,2.0,2.0])
a*b#乘法操作默认是按元素来进行的
#乘以常量
a = np.array([1.0,2.0,3.0])
b = 2.0
a*b


array([ 2.,  4.,  6.])

# 3.数组转置（transpose）和轴对换

In [5]:
#数组转置
arr = np.arange(15).reshape((3,5))
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [6]:
#矩阵内积计算
arr = np.random.randn(6,3)
np.dot(arr.T,arr)

array([[ 3.58782145, -2.07461096,  0.29194708],
       [-2.07461096,  8.24052857,  4.82574595],
       [ 0.29194708,  4.82574595,  8.60213194]])

In [8]:
#对高位数组，转置需要有轴编号组成的元组才能转置
arr = np.arange(16).reshape((2,2,4))
arr.transpose((1,0,2))
arr.swapaxes(1,2)#转置其中的两个轴，只是视图，原数据并不发生变化。

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

# 4.通用函数（ufunc）:元素级操作

In [9]:
#一元ufunc
arr = np.arange(10)
np.sqrt(arr)#求平方根
np.exp(arr)#求自然指数
np.abs(arr)#计算绝对值
np.square(arr)#计算平方
np.log(arr)#自然对数
np.log10(arr)#底数为10的对数
np.log1p(arr)#log(1+x)的对数
np.sign(arr)#计算各元素的正负号
np.ceil(arr)#计算大于等于该值得罪小整数
np.floor(arr)#计算小于等于该值得最大整数
np.rint(arr)#四舍五入到最接近的整数
np.modf(arr)#将数组的小数和整数部分独立的返回
np.isnan(arr)#返回哪些是nan的布尔型数组
np.isfinite(arr)#返回哪些是有穷的
np.isinf(arr)#返回哪些是无穷的
np.cos(arr)#三角函数
np.cosh(arr)
np.sin(arr)
np.sinh(arr)
np.tan(arr)
np.tanh(arr)
np.arccos(arr)#反三角函数
np.arccosh(arr)#反三角函数
np.logical_not(arr)#返回各元素not x的真值

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ])

In [13]:
#二元ufunc
x = np.random.randn(8)
y = np.random.randn(8)
np.maximum(x,y)#返回元素级最大值
np.add#将数组对应元素相加
np.subtract(x,y)#减法
np.multiply(x,y)#乘法
divide、floor_divide#除法，整除
power#计算A^B
maximum,fmax#最大值，fmax忽略NAN
minimum,fmin#最小值
mod#求模计算，除法余数
copysign#将第二个数组的值得符号复制给第一组
greater,greater_equal#比较运算，产生布尔型数组
less,less_equal,equal,not_equal
logical_and,logical_or,logical_xor#逻辑运算。

array([ 1.1079115 ,  1.5995992 ,  0.22917406,  0.84771533,  0.90068898,
        0.53146334, -0.46359146,  0.87433577])

In [15]:
#返回多个数组
arr = np.random.randn(7)*5
np.modf(arr)#返回浮点数的小数部分和整数部分

(array([-0.1328512 , -0.77089373, -0.12626944, -0.1093083 , -0.03433185,
         0.93857552, -0.40806209]), array([-8., -1., -1., -4., -2.,  3., -3.]))

# 5.利用数组进行数据处理